import matplotlib.pyplot as plt
C = complex(1.5,2.6)
fig, ax = plt.subplots()
ax.set_title('Complex number')
ax.set_xlabel('Real')
ax.set_ylabel('Imaginary')
ax.quiver(0,0,C.real, C.imag, angles='xy', scale_units='xy', scale=1,color='blue', label='C=1.5+2.6i')
ax.set_xlim(0,3)
ax.set_ylim(0,3)
ax.grid(True)
ax.axhline(0, color='black',linewidth=0.25)
ax.axvline(0, color='black', linewidth=0.25)
ax.legend()
ax.set_aspect('equal')
plt.show()
